apiVersion: v1
kind: Pod
metadata:
  name: mi-pod
  namespace: tech-prod
spec:
  containers:
    - name: app-python-pod
      image: image01:v1
      resources:
        limits:
          memory: "3Gi"  # Límite máximo de memoria para el contenedor
      ports:
        - containerPort: 8080  # Puerto en el que escucha tu aplicación dentro del contenedor
      env:
        - name: ENV_VAR_NAME
          value: valor_de_variable_de_entorno
  restartPolicy: Always
